package main

// Mockup-dump harness: composes fixture-populated root models at fixed
// dimensions and writes their View() frames to .ans files, so layout
// candidates can be rendered and compared (via freeze) without driving a
// live terminal. Fixture data only — nothing here reads a live store.
//
// Run:
//
//	LORE_MOCKUP_DUMP=1 go test -run TestMockupDump -v
//
// Without LORE_MOCKUP_DUMP=1 every dump test skips, so the harness is inert
// during normal `go test`. Output lands in $LORE_MOCKUP_DIR when set,
// otherwise in the tui-design-exploration-pass work item's captures/
// directory under ~/.lore.
//
// Adding variants — the extension contract:
//
// Each new group of variants lives in its OWN standalone test file (e.g.
// mockup_axis_a_test.go) in this package. A variant is a test function (or
// subtest) that builds a fixture model, renders a frame, and hands it to
// dumpMockup:
//
//	func TestMockupDumpAxisA(t *testing.T) {
//		dumpMockup(t, "cand-worklist-flat", func(t *testing.T) string {
//			m := newMockupModel(t, stateWork, config.LayoutTopBottom,
//				mockupWidth, mockupHeight, myFixtureItems(), nil)
//			return m.viewContent()
//		})
//	}
//
// Do not edit this file to register a variant — there is no registry. Test
// names are the selection mechanism: `go test -run 'TestMockupDumpAxisA'`
// renders one file's variants, `-run 'TestMockupDump'` renders everything.
// dumpMockup provides the skip gate, the output directory, and a
// determinism check (each frame is rendered twice and must be
// byte-identical) — new fixtures that render nondeterministically fail
// instead of producing unstable captures.
//
// Fixture rows flow through the real list/collection render paths; never
// pre-style fixture strings — plain-text truncation before styling is the
// engine's job.

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	tea "charm.land/bubbletea/v2"

	"github.com/anticorrelator/lore/tui/internal/config"
	"github.com/anticorrelator/lore/tui/internal/followup"
	"github.com/anticorrelator/lore/tui/internal/gh"
	"github.com/anticorrelator/lore/tui/internal/settlement"
	"github.com/anticorrelator/lore/tui/internal/work"
)

// mockupWidth/mockupHeight match the tmux capture standard (170×46) so
// headless dumps stay pixel-comparable with live captures.
const (
	mockupWidth  = 170
	mockupHeight = 46
)

// requireMockupDump skips the test unless the dump harness is explicitly
// enabled, mirroring the visual_dump_test.go probe precedent.
func requireMockupDump(t *testing.T) {
	t.Helper()
	if os.Getenv("LORE_MOCKUP_DUMP") != "1" {
		t.Skip("mockup dump disabled — set LORE_MOCKUP_DUMP=1 to write .ans captures")
	}
}

// mockupOutDir resolves the capture output directory: $LORE_MOCKUP_DIR when
// set, otherwise the design-exploration work item's captures/ directory.
// The directory is created if missing.
func mockupOutDir(t *testing.T) string {
	t.Helper()
	dir := os.Getenv("LORE_MOCKUP_DIR")
	if dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			t.Fatalf("resolving home dir for default capture path: %v", err)
		}
		dir = filepath.Join(home, ".lore", "repos", "github.com", "anticorrelator", "lore",
			"_work", "tui-design-exploration-pass", "captures")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("creating capture dir %s: %v", dir, err)
	}
	return dir
}

// dumpMockup is the single entry point for every variant: it applies the
// skip gate, renders the frame twice to prove the fixture is deterministic,
// and writes <name>.ans to the output directory.
func dumpMockup(t *testing.T, name string, render func(t *testing.T) string) {
	t.Helper()
	requireMockupDump(t)

	first := render(t)
	second := render(t)
	if first != second {
		t.Fatalf("mockup %q is nondeterministic: two renders differ (len %d vs %d)",
			name, len(first), len(second))
	}
	if first == "" {
		t.Fatalf("mockup %q rendered an empty frame", name)
	}

	frame := first
	if frame[len(frame)-1] != '\n' {
		frame += "\n"
	}
	path := filepath.Join(mockupOutDir(t), name+".ans")
	if err := os.WriteFile(path, []byte(frame), 0o644); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
	t.Logf("wrote %s (%d bytes)", path, len(frame))
}

// newMockupModel builds a root model populated with fixture lists and sized
// via a real WindowSizeMsg, so every sub-model receives the same dimension
// fan-out as production. Returned commands are discarded — no fixture path
// may depend on executing a Cmd (that is where disk and subprocess I/O live).
func newMockupModel(t *testing.T, state appState, layout config.LayoutMode, width, height int, workItems []work.WorkItem, fuItems []followup.FollowUpItem) model {
	t.Helper()
	m := minimalModel(state, workItems, fuItems)
	m.layoutMode = layout
	m, _ = updateModel(t, m, tea.WindowSizeMsg{Width: width, Height: height})
	return m
}

// withWorkDetail points the detail pane at a fixture detail document,
// mirroring loadDetail's size-then-load sequence without its disk-read Cmd.
func withWorkDetail(t *testing.T, m model, detail *work.WorkItemDetail) model {
	t.Helper()
	m.detail = work.NewDetailModel("", detail.Slug)
	m.detail, _ = m.detail.Update(tea.WindowSizeMsg{Width: m.rightPanelWidth(), Height: m.detailPanelHeight()})
	m.detail, _ = m.detail.Update(work.DetailLoadedMsg{Slug: detail.Slug, Detail: detail})
	m.list.SetCursorBySlug(detail.Slug)
	return m
}

// withSettlementStatus injects a fixture settlement status. Call after
// newMockupModel so the panel is already sized.
func withSettlementStatus(m model, st settlement.Status) model {
	m.settlement = m.settlement.ReplaceStatus(st)
	return m
}

// withPRStatuses marks the PR loader as completed with fixture statuses so
// PR badges render their real states instead of the "..." loading badge.
func withPRStatuses(m model, statuses map[string]gh.PRStatus) model {
	m.list, _ = m.list.Update(work.PRStatusMsg{Statuses: statuses})
	return m
}

// mockupTimeAgo returns an RFC3339 timestamp the given duration before the
// current hour boundary. Truncating to the hour keeps raw timestamps (shown
// verbatim in detail metadata) stable across runs within the same hour, and
// relative labels stay stable indefinitely as long as offsets are day-scale
// with a half-day margin (e.g. 36h → always "1d ago"): the truncation adds
// up to an hour of extra age, so hour- or minute-scale offsets would render
// different labels depending on when the dump runs — don't use them.
func mockupTimeAgo(ago time.Duration) string {
	return time.Now().UTC().Truncate(time.Hour).Add(-ago).Format(time.RFC3339)
}

// mockupWorkItems covers the row states the work list distinguishes:
// project-grouped and ungrouped items, the three readiness levels, and
// issue/PR reference badges.
func mockupWorkItems() []work.WorkItem {
	return []work.WorkItem{
		{
			Slug: "auth-token-refresh", Title: "Auth token refresh flow",
			Status: "active", Project: "auth-hardening",
			Issue:      "https://github.com/example/repo/issues/141",
			PR:         "https://github.com/example/repo/pull/148",
			Updated:    mockupTimeAgo(36 * time.Hour),
			HasPlanDoc: true, HasTasks: true,
		},
		{
			Slug: "session-store-migration", Title: "Session store migration",
			Status: "active", Project: "auth-hardening",
			Updated:    mockupTimeAgo(60 * time.Hour),
			HasPlanDoc: true,
		},
		{
			Slug: "worklist-grouping-rework", Title: "Work list grouping rework",
			Status: "active", Project: "tui-polish",
			Issue:      "205",
			Updated:    mockupTimeAgo(36 * time.Hour),
			HasPlanDoc: true, HasTasks: true,
		},
		{
			Slug: "detail-pane-digest", Title: "Detail pane human digest",
			Status: "active", Project: "tui-polish",
			Updated: mockupTimeAgo(60 * time.Hour),
		},
		{
			Slug: "flaky-capture-timeout", Title: "Flaky capture timeout on CI",
			Status:     "active",
			PR:         "https://github.com/example/repo/pull/152",
			Updated:    mockupTimeAgo(84 * time.Hour),
			HasPlanDoc: true, HasTasks: true,
		},
		{
			Slug: "drift-sweep-batching", Title: "Drift sweep batching",
			Status:  "active",
			Updated: mockupTimeAgo(252 * time.Hour),
		},
	}
}

// mockupPRStatuses pairs with mockupWorkItems: one open+approved PR and one
// merged PR, keyed by the PR field values above.
func mockupPRStatuses() map[string]gh.PRStatus {
	return map[string]gh.PRStatus{
		"https://github.com/example/repo/pull/148": {Number: 148, State: "OPEN", ReviewDecision: "APPROVED"},
		"https://github.com/example/repo/pull/152": {Number: 152, State: "MERGED"},
	}
}

// mockupFollowupItems covers open follow-ups from the two common sources
// with and without attachments.
func mockupFollowupItems() []followup.FollowUpItem {
	return []followup.FollowUpItem{
		{
			ID: "fu-selection-bleed", Title: "Selection background bleeds past panel edge",
			Status: "open", Source: "pr-self-review",
			Created: mockupTimeAgo(50 * time.Hour), Updated: mockupTimeAgo(50 * time.Hour),
			HasFinding: true,
			Attachments: []followup.Attachment{
				{Type: "pr", Ref: "https://github.com/example/repo/pull/148"},
			},
		},
		{
			ID: "fu-keybind-help-drift", Title: "Help modal omits settlement keybinds",
			Status: "open", Source: "retro",
			Created: mockupTimeAgo(108 * time.Hour), Updated: mockupTimeAgo(84 * time.Hour),
		},
		{
			ID: "fu-relative-time-bucket", Title: "Relative time buckets skip weeks",
			Status: "open", Source: "pr-self-review",
			Created: mockupTimeAgo(156 * time.Hour), Updated: mockupTimeAgo(30 * time.Hour),
			HasFinding: true,
		},
	}
}

// mockupWorkDetail is a representative work item document: metadata, a
// plan.md with the sections a digest view would extract (intent, narrative,
// architecture diagram), notes, and tasks.
func mockupWorkDetail() *work.WorkItemDetail {
	plan := `# Auth token refresh flow

## Intent

Expired access tokens currently force a full re-login. Refresh them
transparently so sessions survive token expiry without user-visible
interruption.

## Narrative

The API client learns to detect a 401 with an ` + "`expired_token`" + ` error code,
exchange the refresh token at ` + "`/oauth/refresh`" + `, and replay the original
request once. Refresh failures fall through to the existing logout path, so
the worst case is exactly today's behavior.

## Architecture

` + "```" + `
client request ──> 401 expired_token ──> refresh exchange ──> replay once
                                              │
                                              └─ failure ──> logout path
` + "```" + `

## Phases

1. Detect expiry responses in the client transport.
2. Single-flight the refresh exchange.
3. Replay and backoff policy.
`
	notes := `## 2026-06-28

Single-flighting matters: parallel requests all hit the 401 at once and must
share one refresh exchange, not race five.

## 2026-06-30

Replay only idempotent requests automatically; queue mutations behind the
refresh instead.
`
	return &work.WorkItemDetail{
		Slug:         "auth-token-refresh",
		Title:        "Auth token refresh flow",
		Status:       "active",
		Branches:     []string{"auth/token-refresh"},
		Tags:         []string{"auth", "reliability"},
		Project:      "auth-hardening",
		Issue:        "https://github.com/example/repo/issues/141",
		PR:           "https://github.com/example/repo/pull/148",
		Created:      mockupTimeAgo(156 * time.Hour),
		Updated:      mockupTimeAgo(36 * time.Hour),
		PlanContent:  &plan,
		NotesContent: &notes,
		HasTasks:     true,
		TasksContent: &work.TasksFile{
			Phases: []work.Phase{
				{
					PhaseNumber: 1,
					PhaseName:   "Transport detection",
					Objective:   "Recognize expired-token responses at the client boundary",
					Tasks: []work.Task{
						{ID: "1", Subject: "Detect expired_token responses in transport"},
						{ID: "2", Subject: "Single-flight refresh exchange", BlockedBy: []string{"1"}},
					},
				},
				{
					PhaseNumber: 2,
					PhaseName:   "Replay policy",
					Objective:   "Replay idempotent requests after refresh",
					Tasks: []work.Task{
						{ID: "3", Subject: "Replay policy for idempotent requests", BlockedBy: []string{"2"}},
					},
				},
			},
		},
	}
}

// mockupSettlementStatus populates every region of the settlement panel:
// header, queue (with a running and a blocked row), selected claim,
// verdicts across the outcome spectrum, and an active lease.
func mockupSettlementStatus() settlement.Status {
	return settlement.Status{
		Available: true,
		Enabled:   true,
		Queue:     settlement.Queue{Total: 7, Ready: 2, Pending: 3, Running: 1, Complete: 1},
		Items: []settlement.Item{
			{
				ID: "cl-meta-single-block", WorkItem: "capture-metadata",
				ClaimID:    "meta-single-block",
				Claim:      "All capture metadata flows through a single META string accumulated in one HTML comment block",
				SourceFile: "scripts/capture.sh", LineRange: "147-166",
				Falsifier: "A second independent metadata block elsewhere in the script",
				Status:    "running", Harness: "claude-code",
			},
			{
				ID: "cl-resolve-pure", WorkItem: "fixture-injection",
				ClaimID:    "resolve-repo-pure",
				Claim:      "resolve-repo.sh is a pure path resolver with no agent-disable gate",
				SourceFile: "scripts/resolve-repo.sh", LineRange: "21-26",
				Status: "ready",
			},
			{
				ID: "cl-stale-index", WorkItem: "index-refresh",
				ClaimID: "index-regen-on-missing",
				Claim:   "Missing _index.md is regenerated on first read rather than erroring",
				Status:  "blocked", BlockedReason: "evidence file moved",
			},
		},
		Leases: []settlement.Lease{
			{ID: "lease-01", ItemID: "cl-meta-single-block", WorkerID: "settle-1",
				Harness: "claude-code", PID: 4242, ExpiresAt: "in 12m"},
		},
		Harness: settlement.Harness{
			Mode: "auto", Selected: "claude-code", Concurrency: 2,
			CapTotal: 3600, CapRemaining: 2400, ActiveLeases: 1,
		},
		Usage: settlement.Usage{BudgetState: "ok", CapTotal: 20, CapRemaining: 14},
		RecentSettled: []settlement.LastSettled{
			{ClaimID: "lib-sourcing-standard", Claim: "All scripts source lib.sh via SCRIPT_DIR resolution",
				VerdictLabel:      "verified",
				CorrectionOutcome: settlement.CorrectionOutcome{Status: "applied"}},
			{ClaimID: "hooks-parallel-load", Claim: "SessionStart hooks load knowledge and work items in parallel",
				VerdictLabel: "unverified"},
			{ClaimID: "single-writer-scorecard", Claim: "Scorecard rows are written only through scorecard-append.sh",
				VerdictLabel:      "contradicted",
				CorrectionOutcome: settlement.CorrectionOutcome{Status: "skipped", Reason: "entry archived"}},
		},
		NextAction: "process_next_ready",
		UpdatedAt:  "2026-07-01T09:00:00Z",
	}
}

// TestMockupDump renders the baseline set: one dump per reworked surface in
// the top-bottom design center, plus a side-by-side compatibility frame.
// These double as the worked examples for the extension contract above.
func TestMockupDump(t *testing.T) {
	requireMockupDump(t)

	t.Run("mock-base-worklist-topbottom", func(t *testing.T) {
		dumpMockup(t, "mock-base-worklist-topbottom", func(t *testing.T) string {
			m := newMockupModel(t, stateWork, config.LayoutTopBottom,
				mockupWidth, mockupHeight, mockupWorkItems(), mockupFollowupItems())
			m = withPRStatuses(m, mockupPRStatuses())
			m = withWorkDetail(t, m, mockupWorkDetail())
			return m.viewContent()
		})
	})

	t.Run("mock-base-detail-topbottom", func(t *testing.T) {
		dumpMockup(t, "mock-base-detail-topbottom", func(t *testing.T) string {
			m := newMockupModel(t, stateWork, config.LayoutTopBottom,
				mockupWidth, mockupHeight, mockupWorkItems(), mockupFollowupItems())
			m = withPRStatuses(m, mockupPRStatuses())
			m = withWorkDetail(t, m, mockupWorkDetail())
			m.focusedPanel = panelRight
			return m.viewContent()
		})
	})

	t.Run("mock-base-followups-topbottom", func(t *testing.T) {
		dumpMockup(t, "mock-base-followups-topbottom", func(t *testing.T) string {
			m := newMockupModel(t, stateFollowUps, config.LayoutTopBottom,
				mockupWidth, mockupHeight, mockupWorkItems(), mockupFollowupItems())
			return m.viewContent()
		})
	})

	t.Run("mock-base-settlement", func(t *testing.T) {
		dumpMockup(t, "mock-base-settlement", func(t *testing.T) string {
			m := newMockupModel(t, stateSettlement, config.LayoutTopBottom,
				mockupWidth, mockupHeight, mockupWorkItems(), mockupFollowupItems())
			m = withSettlementStatus(m, mockupSettlementStatus())
			return m.viewContent()
		})
	})

	t.Run("mock-base-worklist-sidebyside", func(t *testing.T) {
		dumpMockup(t, "mock-base-worklist-sidebyside", func(t *testing.T) string {
			m := newMockupModel(t, stateWork, config.LayoutLeftRight,
				mockupWidth, mockupHeight, mockupWorkItems(), mockupFollowupItems())
			m = withPRStatuses(m, mockupPRStatuses())
			m = withWorkDetail(t, m, mockupWorkDetail())
			return m.viewContent()
		})
	})
}
