#!/usr/bin/env bash
# write-execution-log.sh — Append an entry to a work item's execution-log.md
# Usage: write-execution-log.sh --slug <slug> --source <source> [--phase <phase>]
#        Entry body is read from stdin.
# Creates execution-log.md if missing (with header).
# Sources: implement-lead | spec-lead | remember | manual

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

# --- Parse arguments ---
SLUG=""
SOURCE=""
PHASE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --slug)
      SLUG="$2"
      shift 2
      ;;
    --source)
      SOURCE="$2"
      shift 2
      ;;
    --phase)
      PHASE="$2"
      shift 2
      ;;
    *)
      echo "[execution-log] Error: Unknown flag '$1'" >&2
      echo "Usage: write-execution-log.sh --slug <slug> --source <source> [--phase <phase>]" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$SLUG" ]]; then
  echo "[execution-log] Error: --slug is required." >&2
  exit 1
fi

if [[ -z "$SOURCE" ]]; then
  echo "[execution-log] Error: --source is required." >&2
  exit 1
fi

case "$SOURCE" in
  implement-lead|spec-lead|remember|manual) ;;
  *)
    echo "[execution-log] Error: --source must be one of: implement-lead, spec-lead, remember, manual" >&2
    exit 1
    ;;
esac

# --- Resolve paths ---
KNOWLEDGE_DIR=$(resolve_knowledge_dir)
WORK_DIR="$KNOWLEDGE_DIR/_work"
ITEM_DIR="$WORK_DIR/$SLUG"

if [[ ! -d "$ITEM_DIR" ]]; then
  echo "[execution-log] Error: Work item not found: $SLUG" >&2
  exit 1
fi

LOG_FILE="$ITEM_DIR/execution-log.md"

# --- Create log file with header if missing ---
if [[ ! -f "$LOG_FILE" ]]; then
  {
    echo "# Execution Log: $SLUG"
    echo ""
    echo "<!-- Auto-generated by write-execution-log.sh. Do not edit the header. -->"
    echo ""
  } > "$LOG_FILE"
fi

# --- Read entry body from stdin ---
ENTRY_BODY=$(cat)

# --- Build entry header ---
TIMESTAMP=$(timestamp_iso)

PHASE_LABEL=""
if [[ -n "$PHASE" ]]; then
  PHASE_LABEL=" | phase: $PHASE"
fi

# --- Append entry ---
{
  echo "## $TIMESTAMP | source: $SOURCE$PHASE_LABEL"
  echo ""
  echo "$ENTRY_BODY"
  echo ""
} >> "$LOG_FILE"

echo "[execution-log] Entry written to $LOG_FILE"
